In [2]:
#Importação das bibliotecas
import os
import glob
import pandas as pd

#Ler dados brutos e salvar dados limpos
BASE_DIR = os.path.dirname(os.getcwd()) # Sobe um nível para a raiz do projeto
RAW_DATA_DIR = os.path.join(BASE_DIR, "data", "raw")
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, "data", "processed")

#Garante que a pasta processed existe
os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)

#Localizar todos os arquivos CSV na pasta data/raw
csv_files = glob.glob(os.path.join(RAW_DATA_DIR, "bdqueimadas_*.csv"))
print(f"Encontrados {len(csv_files)} arquivos para processar:")
for f in csv_files:
    print(f" - {os.path.basename(f)}")
    
#Ler e concatenar todos os arquivos em um único DataFrame
df_list = []
for file in csv_files:
    try:
        temp_df = pd.read_csv(file, encoding='utf-8')
    except UnicodeDecodeError:
        temp_df = pd.read_csv(file, encoding='iso-8859-1')
    
    # Adiciona uma coluna identificando a origem do arquivo
    temp_df['source_file'] = os.path.basename(file)
    df_list.append(temp_df)
    
# Concatenando todos os dataframes verticalmente
df_raw = pd.concat(df_list, ignore_index=True)

print("\n--- Concatenação Concluída ---")
print(f"Total de registros importados: {df_raw.shape[0]:,}")
print(f"Total de colunas originais: {df_raw.shape[1]}")

Encontrados 6 arquivos para processar:
 - bdqueimadas_2026-01-02_2026-07-16.csv
 - bdqueimadas_2022-01-02_2023-01-01.csv
 - bdqueimadas_2023-01-02_2024-01-01.csv
 - bdqueimadas_2025-07-02_2026-01-01.csv
 - bdqueimadas_2024-01-02_2025-01-01.csv
 - bdqueimadas_2021-01-01_2022-01-01.csv

--- Concatenação Concluída ---
Total de registros importados: 992,026
Total de colunas originais: 13

In [11]:
# 1. Visualizar as primeiras linhas
display(df_raw.head())
print("-------------------------------------------")

# 2. Verificar tipos de dados e valores nulos
print("\n--- Informações do DataFrame ---")
df_raw.info()

print("-------------------------------------------")
# 3. Validar a quantidade de valores nulos por coluna
print("\n--- Valores Nulos por Coluna ---")
nulos = df_raw.isnull().sum()
percent_nulos = (df_raw.isnull().sum() / len(df_raw)) * 100
df_missing = pd.DataFrame({'Total Nulos': nulos, 'Percentual (%)': percent_nulos})
display(df_missing[df_missing['Total Nulos'] > 0])

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude,source_file
0,2026/01/02 18:06:00,AQUA_M-T,Brasil,SANTA CATARINA,ITAIÓPOLIS,Mata Atlântica,5.0,1.66,0.03,34.2,-26.34281,-50.01770,bdqueimadas_2026-01-02_2026-07-16.csv
1,2026/01/02 18:06:00,AQUA_M-T,Brasil,SANTA CATARINA,ITAIÓPOLIS,Mata Atlântica,6.0,1.68,0.02,36.5,-26.34253,-50.02262,bdqueimadas_2026-01-02_2026-07-16.csv
2,2026/01/02 18:08:00,AQUA_M-T,Brasil,MINAS GERAIS,BURITIZEIRO,Cerrado,0.0,0.00,0.01,16.1,-17.65578,-45.32652,bdqueimadas_2026-01-02_2026-07-16.csv
3,2026/01/02 18:08:00,AQUA_M-T,Brasil,MINAS GERAIS,TARUMIRIM,Mata Atlântica,13.0,0.00,0.96,9.3,-19.40587,-41.84436,bdqueimadas_2026-01-02_2026-07-16.csv
4,2026/01/02 18:08:00,AQUA_M-T,Brasil,MINAS GERAIS,RIO VERMELHO,Mata Atlântica,11.0,4.67,0.00,10.0,-18.16236,-42.92531,bdqueimadas_2026-01-02_2026-07-16.csv

-------------------------------------------

--- Informações do DataFrame ---
<class 'pandas.DataFrame'>
RangeIndex: 992026 entries, 0 to 992025
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   DataHora      992026 non-null  str
 1   Satelite      992026 non-null  str
 2   Pais          992026 non-null  str
 3   Estado        992026 non-null  str
 4   Municipio     992026 non-null  str
 5   Bioma         992026 non-null  str
 6   DiaSemChuva   991795 non-null  float64
 7   Precipitacao  991795 non-null  float64
 8   RiscoFogo     991795 non-null  float64
 9   FRP           992026 non-null  float64
 10  Latitude      992026 non-null  float64
 11  Longitude     992026 non-null  float64
 12  source_file   992026 non-null  str
dtypes: float64(6), str(7)
memory usage: 98.4 MB
-------------------------------------------

--- Valores Nulos por Coluna ---

              Total Nulos  Percentual (%)
DiaSemChuva           231        0.023286
Precipitacao          231        0.023286
RiscoFogo             231        0.023286